import { execSync } from "node:child_process";
// vitest/config, not vite: it is the one that also types the `test` block below, so the
// config needs no `as any` cast to carry both halves.
import { defineConfig } from "vitest/config";
import type { PluginContext } from "rollup";

/**
 * A stamp of what is actually running, shown on the Settings screen.
 *
 * Milan tests the deployed build on his phone, where a stale cached page and a real bug
 * look exactly alike from the outside. Being able to read the commit off the screen turns
 * "it does not work" into a one-line answer.
 */
const buildStamp = (): string => {
  try {
    const sha = execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString().trim();
    const day = new Date().toISOString().slice(0, 10);
    return `${sha} · ${day}`;
  } catch {
    return "dev";
  }
};

const STAMP = buildStamp();

/**
 * The offline service worker, as source.
 *
 * Written out rather than pulled from a plugin so the whole of it is readable in one place
 * — it is ninety lines and the rules in it are ours, not a framework's.
 *
 * THREE KINDS OF REQUEST, three answers, and the differences are the entire design:
 *
 *  - `version.json` is NETWORK ONLY. `platform/freshness.ts` reads it to notice a newer
 *    build; answering it from a cache would tell the app it is current for ever and pin the
 *    device to a stale bundle — the exact bug freshness exists to fix, made permanent.
 *  - a NAVIGATION is network-first, falling back to the cached page. The app reloads itself
 *    onto `?v=<commit>` after a deploy, so the query has to be ignored when matching, or
 *    that reload would miss the cache and fail offline.
 *  - everything else is cache-first. Vite content-hashes the filenames, so a name that is
 *    in the cache can never be stale — which is what makes this safe to serve without
 *    asking the network at all.
 *
 * The fonts are cross-origin and cached OPPORTUNISTICALLY: they cannot be precached (an
 * install that fails on one URL fails entirely, and Google's CSS is not ours to depend on),
 * but once they have been fetched a second visit has them offline.
 */
function serviceWorker(precache: string[]): string {
  return `/* Generated by vite.config.ts — do not edit. Build: ${STAMP} */
const BUILD = ${JSON.stringify(STAMP)};
const CACHE = "zombie-ants:" + BUILD;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener("install", (e) => {
  // One at a time and never fatal: a single 404 in addAll() throws the whole install away
  // and leaves the player with no offline game at all.
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await Promise.all(PRECACHE.map((url) => cache.add(url).catch(() => {})));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    // Every other build's cache goes. The names are content-hashed, so nothing shared
    // between two builds is ever thrown away twice.
    const keys = await caches.keys();
    await Promise.all(keys.map((k) => (k !== CACHE && k.startsWith("zombie-ants:")
      ? caches.delete(k) : Promise.resolve(false))));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);

  // NETWORK ONLY. See the note in vite.config.ts: caching this pins the app to a stale build.
  if (url.pathname.endsWith("/version.json")) return;

  // A NAVIGATION: try the network, fall back to the page we have. \`ignoreSearch\` is what
  // makes the post-deploy reload onto "?v=<commit>" still match offline.
  if (req.mode === "navigate") {
    e.respondWith((async () => {
      try {
        return await fetch(req);
      } catch {
        const cache = await caches.open(CACHE);
        return (await cache.match(req, { ignoreSearch: true }))
          ?? (await cache.match("./index.html"))
          ?? Response.error();
      }
    })());
    return;
  }

  // EVERYTHING ELSE: cache first, because the names are hashed and cannot go stale. What
  // is not there is fetched and kept — which is how the cross-origin fonts end up offline
  // on the second visit without the install having to depend on them.
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const res = await fetch(req);
      // Opaque responses (the fonts) have status 0 and are still worth keeping.
      if (res && (res.ok || res.type === "opaque")) await cache.put(req, res.clone());
      return res;
    } catch {
      return (await cache.match(req, { ignoreSearch: true })) ?? Response.error();
    }
  })());
});
`;
}

export default defineConfig({
  base: "./",                    // relative paths so the build works in a Capacitor shell
  define: { __BUILD__: JSON.stringify(STAMP) },
  plugins: [{
    name: "zombie-ants:version-and-worker",
    generateBundle(this: PluginContext, _options, bundle) {
      // The same stamp, as a file the running app can ask for. Pages caches the HTML, so a
      // device can sit on the previous bundle for minutes after a deploy; this is what lets
      // the app notice and take the new one (src/platform/freshness.ts).
      this.emitFile({
        type: "asset",
        fileName: "version.json",
        source: JSON.stringify({ build: STAMP }),
      });
      // THE OFFLINE WORKER IS WRITTEN HERE because only the build knows the names it has
      // just emitted — they are content-hashed, so a hand-written list would be wrong on
      // the first commit that changed a byte (src/platform/offline.ts).
      this.emitFile({
        type: "asset",
        fileName: "sw.js",
        source: serviceWorker([
          "./",
          "./index.html",
          "./manifest.webmanifest",
          "./icon-192.png",
          "./apple-touch-icon.png",
          "./favicon-64.png",
          // Everything the build just emitted — EXCEPT `version.json`, which the worker
          // deliberately never answers from a cache (see below). Precaching it would be a
          // file kept for a request that can never reach it.
          ...Object.keys(bundle)
            .filter((name) => name !== "version.json")
            .map((name) => `./${name}`),
        ]),
      });
    },
  }],
  build: { outDir: "dist", target: "es2020" },
  test: {
    globals: true,
    include: ["src/**/*.test.ts"],
    // The engine is pure and runs fastest with no DOM at all; only the screens need one,
    // so jsdom is switched on per directory rather than globally.
    environment: "node",
    /*
     * jsdom where a test needs a DOM. The screens obviously do — and so does the board
     * RENDERER, which owns a canvas, a ResizeObserver and an animation frame, and was the
     * one file in `render/` with no test at all because of it. The rest of `render/` is
     * pure drawing against a recorded context and stays in node, which is faster.
     */
    environmentMatchGlobs: [
      ["src/ui/**", "jsdom"],
      ["src/render/__tests__/renderer.test.ts", "jsdom"],
    ],
  },
});
