/**
 * PLAYING WITH NO NETWORK.
 *
 * Two halves are worth holding here, and they are very different in kind.
 *
 * The REGISTRATION is a few lines that must never throw: every way it can fail — no
 * support, plain http, storage refused — means only that the game needs the network, which
 * is what it needed before, and none of it may stop the game starting.
 *
 * The WORKER ITSELF is generated by the build (`vite.config.ts`), because only the build
 * knows the hashed filenames. That makes it the one piece of shipped code with no module to
 * import, so the rules in it are asserted against its SOURCE — crude, and far better than
 * the alternative, which is the single most dangerous bug this feature can have: a worker
 * that answers `version.json` out of its cache tells the app it is up to date for ever and
 * pins the device to a stale build, which is the exact bug `freshness.ts` exists to fix,
 * made permanent and much harder to see.
 */
import { afterEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { goOffline, resetOffline } from "../offline";

afterEach(() => { resetOffline(); vi.unstubAllGlobals(); });

describe("asking for the worker", () => {
  const spy = (): { register: ReturnType<typeof vi.fn> } => {
    const register = vi.fn(() => Promise.resolve({}));
    vi.stubGlobal("navigator", { serviceWorker: { register } });
    vi.stubGlobal("document", { readyState: "complete" });
    vi.stubGlobal("window", { addEventListener: vi.fn() });
    return { register };
  };

  it("registers the worker beside the page, never at the domain root", () => {
    const { register } = spy();
    goOffline();
    expect(register).toHaveBeenCalledTimes(1);
    // Relative: the game lives under a project path on Pages and inside a native shell,
    // and "/sw.js" would be outside its scope in both.
    expect(register.mock.calls[0]?.[0]).toBe("./sw.js");
  });

  it("asks once, however many times it is called", () => {
    const { register } = spy();
    goOffline();
    goOffline();
    goOffline();
    expect(register).toHaveBeenCalledTimes(1);
  });

  it("waits for load rather than competing with the bundle it is caching", () => {
    const register = vi.fn(() => Promise.resolve({}));
    const listen = vi.fn();
    vi.stubGlobal("navigator", { serviceWorker: { register } });
    vi.stubGlobal("document", { readyState: "loading" });
    vi.stubGlobal("window", { addEventListener: listen });

    goOffline();
    expect(register, "registered while the page was still loading").not.toHaveBeenCalled();
    expect(listen.mock.calls[0]?.[0]).toBe("load");
    // ...and it really does register when that fires.
    (listen.mock.calls[0]?.[1] as () => void)();
    expect(register).toHaveBeenCalledTimes(1);
  });

  it("says nothing and does nothing where there is no support", () => {
    vi.stubGlobal("navigator", {});
    expect(() => goOffline()).not.toThrow();
  });

  /** Private browsing can throw on the accessor itself, not just return undefined. */
  it("survives a browser that throws when asked", () => {
    vi.stubGlobal("navigator", {
      get serviceWorker(): never { throw new Error("blocked"); },
    });
    expect(() => goOffline()).not.toThrow();
  });

  it("survives a registration that rejects", () => {
    const register = vi.fn(() => Promise.reject(new Error("nope")));
    vi.stubGlobal("navigator", { serviceWorker: { register } });
    vi.stubGlobal("document", { readyState: "complete" });
    vi.stubGlobal("window", { addEventListener: vi.fn() });
    expect(() => goOffline()).not.toThrow();
  });
});

/**
 * The worker's rules, read off the generator in `vite.config.ts`.
 *
 * A source-level assertion is a blunt instrument and it is the right one here: this code
 * has no import, and the alternative is that the most damaging failure in the feature — a
 * permanently stale app — is held by nothing at all.
 */
describe("the generated worker", () => {
  const config = readFileSync(resolve(__dirname, "../../../vite.config.ts"), "utf8");
  const worker = config.slice(config.indexOf("function serviceWorker("));
  /** The same, with the prose stripped — a rule must be in the CODE, not in a comment. */
  const code = worker.replace(/\/\/[^\n]*/g, "").replace(/\/\*[\s\S]*?\*\//g, "");

  /** THE ONE THAT MATTERS. See the note above. */
  it("never answers version.json from a cache", () => {
    expect(code).toContain('url.pathname.endsWith("/version.json")');
    // It must RETURN before responding — not fall through to the cache-first branch.
    const line = code.slice(code.indexOf('endsWith("/version.json")'));
    expect(line.slice(0, 40)).toContain("return");
  });

  /**
   * `freshness.ts` reloads onto "?v=<commit>". Matching with the query string included
   * would miss the cache on exactly that reload, so a post-deploy launch would need the
   * network — the one launch most likely not to have it.
   */
  it("ignores the query when matching, so the post-deploy reload works offline", () => {
    expect(code).toContain("ignoreSearch: true");
  });

  it("falls back to the cached page when a navigation cannot reach the network", () => {
    expect(code).toContain('req.mode === "navigate"');
    expect(code).toContain('cache.match("./index.html")');
  });

  /** A single 404 in addAll() throws the whole install away — no offline game at all. */
  it("installs file by file, so one missing asset cannot lose the lot", () => {
    expect(code).toContain("cache.add(url).catch(() => {})");
    expect(code, "addAll is all-or-nothing").not.toContain("addAll");
  });

  it("throws away other builds' caches, and only ours", () => {
    expect(code).toContain('k.startsWith("zombie-ants:")');
    expect(code).toContain("caches.delete(k)");
  });

  it("keeps opaque responses, which is how the fonts end up offline", () => {
    expect(code).toContain('res.type === "opaque"');
  });

  it("leaves anything that is not a GET alone", () => {
    expect(code).toContain('req.method !== "GET"');
  });
});
