/**
 * PLAYING WITH NO NETWORK.
 *
 * The game is a static bundle and a save in `localStorage` — there is no server anywhere in
 * it (§9) — so there was never a reason it needed to be online, and yet a tunnel, a plane or
 * a bad signal gave a blank page. For a turn-based game somebody plays in exactly those
 * places, that was the largest missing thing in the app.
 *
 * The worker itself is GENERATED BY THE BUILD (`vite.config.ts`), because only the build
 * knows the hashed filenames it has just emitted. This file is the small half: asking the
 * browser for it, once, without ever letting that failure matter.
 *
 * IT MUST NOT FIGHT `freshness.ts`. That reads `version.json` with the cache bypassed and
 * reloads onto `?v=<commit>` when a newer build is out. If the worker ever answered
 * `version.json` from its cache, the app would be told it is up to date for ever and stay
 * pinned to a stale build — the exact bug freshness exists to fix, made permanent and much
 * harder to see. So the worker is written to keep that one file on the network, always.
 */

/** Registered once per page. A second call is harmless, but there is no reason for one. */
let asked = false;

/**
 * Ask the browser to install the offline worker.
 *
 * Deliberately fire-and-forget and deliberately silent. Every failure here — no support, a
 * page served over plain http, storage refused, a worker that will not parse — means only
 * that the game needs the network, which is what it needed before. None of it is worth a
 * message to a player, and none of it may stop the game starting.
 */
export function goOffline(): void {
  if (asked) return;
  asked = true;
  try {
    if (!("serviceWorker" in navigator)) return;
    // Registered AFTER load. A service worker install competes for bandwidth with the
    // bundle it is caching, and the first paint matters more than the second visit.
    const start = (): void => { void navigator.serviceWorker.register("./sw.js").catch(() => {}); };
    if (document.readyState === "complete") start();
    else window.addEventListener("load", start, { once: true });
  } catch {
    /* a browser that throws on the accessor itself is simply a browser without this */
  }
}

/** Test seam: forget that we registered, so a case can run the guard again. */
export const resetOffline = (): void => { asked = false; };
